### ISSUE TITLE
Cut a new image

### ISSUE THREAD

**Issue by foklepoint** [getsentry/sentry-kubernetes#8]
Cut a new sentry-kubernetes image. The upstream raven client includes fixes around parsing DSN that we need to parse our public DSN.

**Comment by bretthoerner** [comment]
Can you try `getsentry/kubernetes:new-deps`? That's this branch: https://github.com/getsentry/sentry-kubernetes/pull/9/files

**Comment by foklepoint** [comment]
Seeing this in logs:
```
TypeError: float() argument must be a string or a number, not 'datetime.datetime'
2018-04-26 17:16:51,648 Unhandled exception occurred.
Traceback (most recent call last):
  File "./sentry-kubernetes.py", line 47, in main
    watch_loop()
  File "./sentry-kubernetes.py", line 185, in watch_loop
    timestamp=creation_timestamp,
  File "/usr/local/lib/python3.6/site-packages/raven/breadcrumbs.py", line 121, in record
    data, type, processor)
  File "/usr/local/lib/python3.6/site-packages/raven/breadcrumbs.py", line 51, in record
    'timestamp': float(timestamp),
TypeError: float() argument must be a string or a number, not 'datetime.datetime'
2018-04-26 17:16:51,751 Unhandled exception occurred.
Traceback (most recent call last):
  File "./sentry-kubernetes.py", line 47, in main
    watch_loop()
  File "./sentry-kubernetes.py", line 185, in watch_loop
    timestamp=creation_timestamp,
  File "/usr/local/lib/python3.6/site-packages/raven/breadcrumbs.py", line 121, in record
    data, type, processor)
  File "/usr/local/lib/python3.6/site-packages/raven/breadcrumbs.py", line 51, in record
    'timestamp': float(timestamp),
TypeError: float() argument must be a string or a number, not 'datetime.datetime'
2018-04-26 17:16:51,852 Unhandled exception occurred.
Traceback (most recent call last):
  File "./sentry-kubernetes.py", line 47, in main
    watch_loop()
  File "./sentry-kubernetes.py", line 185, in watch_loop
    timestamp=creation_timestamp,
  File "/usr/local/lib/python3.6/site-packages/raven/breadcrumbs.py", line 121, in record
    data, type, processor)
```

**Comment by bretthoerner** [comment]
Guess the API changed under me. I pushed an update to that image tag, can you pull and try again?

**Comment by foklepoint** [comment]
Not seeing any error logs which is good and the container is stable. Guess i'll report back when I start seeing events in sentry

**Comment by bretthoerner** [comment]
Yes, please let me know if it works for you and I'll merge it. Thanks.

**Comment by gianrubio** [comment]
@bretthoerner can you cut the images using a consistent version nomenclature? It'll be easier for me to maintain the helm charts.

**Comment by bretthoerner** [comment]
@gianrubio Do you just mean giving them a real version tag instead of using `latest`, or something else?

**Comment by bretthoerner** [comment]
@foklepoint Has this branch been working for you?

**Comment by gianrubio** [comment]
> do you just mean giving them a real version tag instead of using latest, or something else?

Yes, I do! 👍

**Comment by bretthoerner** [comment]
I pushed this up as `getsentry/kubernetes:v0.0.1` for now.
